/* =============================================================================
   FILE:    js/08-review.js
   PROJECT: AMPS CCMC Submission Interface  v3
   PURPOSE: Step 10 — Review, AMPS_PARAM.in file builder, run manifest,
            client-side validation, job submission, and sidebar summary.

   AMPS_PARAM.in FILE BUILDER  (buildReview)
     Generates a complete, commented AMPS_PARAM.in file from the current
     state object S.  Output is rendered into the #review-param element as
     colour-coded HTML using .kw-strip span classes, and can be:
       · Copied to clipboard  (copyParam)
       · Downloaded as a .in text file  (downloadParam)

     The param-file structure mirrors the AMPS v2025 input specification:
       #RUN_ID, #PARTICLE, #FIELD_MODEL + model-specific block,
       #DOMAIN_BOUNDARY, #ELECTRIC_FIELD, #TEMPORAL, #SPECTRUM, #OUTPUT

   RUN MANIFEST  (buildManifest)
     Lists all expected output files so users know what to retrieve after
     the run completes on the CCMC cluster.  Depends on output mode and
     energy bin count.

   VALIDATION  (buildValidation)
     Scans S for potentially dangerous or unusual configurations and
     returns an array of {level, text} warning objects:
       'ok'   — configuration looks standard
       'warn' — unusual but may be intentional (shown in amber)
       'error'— configuration will cause AMPS to fail (shown in red)

   SIDEBAR SUMMARY  (updateSidebar)
     Lightweight function called after every user interaction.
     Writes a one-line summary of each wizard step into the fixed
     right-hand sidebar for at-a-glance status.
     Also updates the progress bar fill (# done steps / 9).

   PUBLIC API
     buildReview()     — render full AMPS_PARAM.in preview into #review-param
     copyParam()       — copy plain-text param file to clipboard
     downloadParam()   — trigger browser download of amps_param.in
     buildManifest()   — return HTML string listing output files
     buildValidation() — return array of validation messages
     finalSubmit()     — submit the run to CCMC (triggers confirm dialog)
     updateSidebar()   — refresh the right-hand sidebar summary
     openHelpModal()   — show the help overlay

   DEPENDS ON: 01-state.js (S, $, set),
               03-bgfield.js (S.fieldModel),
               04-boundary.js (S.boundaryType, shueCalc),
               05-efield.js (S.eFieldCoro, S.eFieldConvModel)
=============================================================================*/

function buildReview(){
  const {r0,alpha}=getShue();
  const isM=S.shueMode==='manual';
  const f=(v,d)=>Number(v).toFixed(d);
  const txt=[
`! ═══════════════════════════════════════════════════════════════
! AMPS_PARAM.in — generated by CCMC Runs-on-Request interface
! Run: ${S.runName||'unnamed'}
! ═══════════════════════════════════════════════════════════════

#RUN_INFO
RUN_ID                 ${S.runName||'unnamed'}
PI_NAME                ${S.piName||'Unknown'}
PI_EMAIL               ${S.piEmail||'unknown@unknown.edu'}
SCIENCE_GOAL           ${$('science-goal')?.value||'custom'}

#PARTICLE_SPECIES
SPECIES                ${S.species.toUpperCase()}
CHARGE                 ${S.charge}               ! elementary charge
MASS_AMU               ${S.mass}           ! atomic mass units

#BACKGROUND_FIELD
FIELD_MODEL            ${S.fieldModel}
TS05_DST               ${f(S.dst,1)}         ! nT ring current index
TS05_PDYN              ${f(S.pdyn,2)}          ! nPa dynamic pressure
TS05_BZ                ${f(S.bz,2)}         ! nT IMF Bz GSM
TS05_VX                ${f(S.vx,1)}       ! km/s solar wind Vx
TS05_NSW               ${f(S.nsw,2)}         ! cm-3 proton density
TS05_BY                ${f(S.by,2)}          ! nT IMF By
TS05_BX                ${f(S.bx,2)}          ! nT IMF Bx
EPOCH                  ${S.epoch}  ! UTC snapshot

#DOMAIN_BOUNDARY
BOUNDARY_TYPE          ${S.boundaryType}${S.boundaryType==='SHUE'?'  ! Shue et al. 1998 magnetopause':'  ! rectangular box in GSM'}`,
S.boundaryType==='BOX'?`DOMAIN_X_MAX           ${f(S.boxXmax,1)}         ! RE dayside
DOMAIN_X_MIN           ${f(S.boxXmin,1)}        ! RE nightside
DOMAIN_Y_MAX           ${f(S.boxYmax,1)}         ! RE dusk
DOMAIN_Y_MIN           ${f(S.boxYmin,1)}        ! RE dawn
DOMAIN_Z_MAX           ${f(S.boxZmax,1)}         ! RE north
DOMAIN_Z_MIN           ${f(S.boxZmin,1)}        ! RE south
R_INNER                ${f(S.boxRinner,1)}           ! RE inner loss sphere`:
`SHUE_R0                ${isM?f(r0,2):'AUTO'}            ! RE; AUTO = from TS05 Bz,Pdyn
SHUE_ALPHA             ${isM?f(alpha,3):'AUTO'}         ! flaring; AUTO = from TS05
DOMAIN_X_TAIL          ${f(S.xtail,1)}        ! RE nightside cap
R_INNER                ${f(S.shueRinner,1)}           ! RE inner loss sphere`,
`
#TEMPORAL
TEMPORAL_MODE          ${S.tempMode}`,
S.tempMode!=='STEADY_STATE'?`EVENT_START            ${S.eventStart}   ! UTC
EVENT_END              ${S.eventEnd}   ! UTC
FIELD_UPDATE_DT        ${S.fieldDt}                ! min
INJECT_DT              ${S.injectDt}               ! min
TS_INPUT_MODE          ${S.tsSource==='omni'?'OMNIWEB':S.tsSource==='file'?'FILE':'SCALAR'}`:
`EPOCH                  ${S.epoch}`,
`
#SPECTRUM
SPECTRUM_TYPE          ${S.specType}
SPEC_J0                ${S.specJ0.toExponential(2)}   ! p/cm2/s/sr/(MeV/n)
SPEC_GAMMA             ${f(S.specGamma,2)}         ! spectral index
SPEC_E0                ${f(S.specE0,1)}          ! MeV/n pivot
SPEC_EMIN              ${f(S.specEmin,1)}          ! MeV/n
SPEC_EMAX              ${f(S.specEmax,1)}       ! MeV/n

#OUTPUT_DOMAIN
OUTPUT_MODE            ${S.outputMode}
FLUX_DT                ${f(S.fluxDt,1)}           ! min output cadence

#OUTPUT_OPTIONS
FLUX_TYPE              ${S.fluxType}
OUTPUT_CUTOFF          ${$('output-cutoff')?.checked?'T':'F'}                    ! cutoff rigidity maps
OUTPUT_PITCH           ${$('output-pitch')?.checked?'T':'F'}                    ! pitch angle distributions
OUTPUT_FORMAT          ${$('output-format')?.value||S.outputFormat}
OUTPUT_COORDS          ${$('output-coords')?.value||S.outputCoords}
ENERGY_BINS            ${S.energyBins.join(' ')}   ! MeV/n

#NUMERICAL
N_PARTICLES            10000              ! test particles per injection
MAX_BOUNCE             500                ! max mirror reflections
DT_TRACE               1.0               ! s integration step
PITCH_ISOTROPIC        T                 ! isotropic injection

#END`
].join('\n');

  const el=$('review-param'); if(!el) return;
  el.innerHTML=txt
    .replace(/^(#\w[\w_]*)/gm,'<span class="r-section">$1</span>')
    .replace(/^(! .+)/gm,'<span class="r-comment">$1</span>')
    .replace(/(AUTO)/g,'<span class="r-auto">AUTO</span>');

  buildManifest(); buildValidation();
  return txt;
}

function copyParam(){ navigator.clipboard.writeText(buildReview().replace(/<[^>]+>/g,'')).then(()=>{ const b=$('copy-param'); if(b){b.textContent='✓ Copied';setTimeout(()=>{b.textContent='📋 Copy';},2000);} }); }
function downloadParam(){
  const txt=(buildReview()||'').replace(/<[^>]+>/g,'');
  const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([txt],{type:'text/plain'}));
  a.download='AMPS_PARAM.in'; a.click();
}

function buildManifest(){
  const tb=$('manifest-tbody'); if(!tb) return;
  const files=[
    {name:'AMPS_PARAM.in',      role:'Main configuration',            req:true, auto:true,  ok:true},
    {name:'AMPS_MANIFEST.json', role:'Run metadata (auto-generated)', req:true, auto:true,  ok:true},
    {name:'trajectory.txt',     role:'Spacecraft trajectory (Mode B)',req:S.outputMode==='TRAJECTORY', auto:false, ok:S.trajLoaded},
    {name:'ts05_driving.txt',   role:'TS05 time-series drivers',      req:S.tempMode==='TIME_SERIES'&&S.tsSource==='file', auto:S.tsSource==='omni', ok:true},
    {name:'sep_spectrum_H+.txt',role:'Spectrum table (if TABLE mode)',req:S.specType==='TABLE', auto:false, ok:S.specType!=='TABLE'},
  ];
  tb.innerHTML=files.filter(f=>f.req||f.auto).map(f=>`
    <tr>
      <td style="font-family:var(--font-mono);color:var(--text)">${f.name}</td>
      <td style="color:var(--text-dim)">${f.role}</td>
      <td style="color:${f.req?'var(--text)':'var(--text-muted)'}">${f.req?'Required':'Optional'}</td>
      <td style="color:${f.auto?'var(--green)':'var(--text-dim)'}">${f.auto?'Auto-generated':'User upload'}</td>
      <td class="${f.ok?'vt-pass':'vt-fail'}">${f.ok?'✓ READY':'✗ MISSING'}</td>
    </tr>`).join('');
}

function buildValidation(){
  const {r0,alpha}=getShue();
  const chks=[
    {l:'Run name set',           ok:!!(S.runName?.trim())},
    {l:'PI email valid',         ok:/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test($('pi-email')?.value||'')},
    {l:'Dst in TS05 range',      ok:S.dst>=-600&&S.dst<=50},
    {l:'Pdyn > 0.1 nPa',         ok:S.pdyn>0.1},
    {l:'Domain boundary set',    ok:['BOX','SHUE'].includes(S.boundaryType)},
    {l:'Shue r₀ plausible (5–13 RE)', ok:S.boundaryType!=='SHUE'||( r0>5&&r0<13)},
    {l:'Inject Δt ≥ Field Update', ok:S.tempMode==='STEADY_STATE'||S.injectDt>=S.fieldDt},
    {l:'Energy bins defined',    ok:S.energyBins.length>0},
    {l:'Spectrum type selected', ok:['POWER_LAW','BAND','TABLE'].includes(S.specType)},
    {l:'Output mode selected',   ok:['POINTS','TRAJECTORY','SHELLS'].includes(S.outputMode)},
    {l:'Trajectory file loaded', ok:S.outputMode!=='TRAJECTORY'||S.trajLoaded, warn:true},
  ];
  const pass=chks.filter(c=>c.ok).length;
  const fail=chks.filter(c=>!c.ok&&!c.warn).length;
  const warn=chks.filter(c=>!c.ok&&c.warn).length;
  const rs=$('review-summary');
  if(rs) rs.innerHTML=`<span class="v-ok">✓ ${pass} passed</span> · <span class="v-warn">⚠ ${warn} warning</span> · <span class="v-err">✗ ${fail} fatal</span>`;
  const rc=$('review-checks'); if(rc){ rc.innerHTML='';
    chks.forEach(c=>{ const d=document.createElement('div');
      d.className='review-item '+(c.ok?'ri-ok':c.warn?'ri-warn':'');
      d.innerHTML=`<div class="ri-label">${c.l}</div><div class="ri-val">${c.ok?'✓ PASS':c.warn?'⚠ WARN':'✗ FAIL'}</div>`;
      rc.appendChild(d); }); }
  const sb=$('submit-btn-final'); if(sb) sb.disabled=fail>0;
}

function finalSubmit(){
  const m=$('submit-modal'); if(m) m.style.display='flex';
}

/* ── 6. SIDEBAR ──────────────────────────────────────────────────── */
function updateSidebar(){
  const set=(id,v,cls)=>{ const e=$(id); if(e){e.textContent=v;if(cls)e.className='sb-v '+cls;} };
  set('sb-run-name', S.runName||'(not set)', S.runName?'':'o');
  set('sb-species',  S.species==='proton'?'H⁺ Proton':S.species==='helium'?'He²⁺':S.species==='electron'?'e⁻':S.species,'g');
  // Sidebar must reflect the actual user-selected background B-field model.
  // (Previously this was hard-coded to 'TS05', which made the review summary incorrect.)
  const prettyField = {
    TS05: 'TS05 (Tsyganenko 2005)',
    T04S: 'T04s (Tsyganenko 2004 storm)',
    T96:  'T96 (Tsyganenko 1996)',
    T95M: 'T95m (modified Tsyganenko 1995)',
    T15:  'T15 (Tsyganenko 2015)',
    BATSRUS: 'BATSRUS (MHD input)',
    GAMERA:  'GAMERA (MHD input)'
  };
  set('sb-field-model', prettyField[S.fieldModel] || S.fieldModel || '—', 'g');
  set('sb-boundary', S.boundaryType==='SHUE'?'Shue 1998':'Box (GSM)','g');
  set('sb-temporal', S.tempMode.replace('_',' '),'');
  set('sb-spec-type', S.specType.replace('_',' '),'');
  set('sb-output-mode', S.outputMode.replace('_',' '),'g');
  const pct=Math.round((S.done.size/9)*100);
  const pf=$('progress-fill'); if(pf) pf.style.width=pct+'%';
  const pp=$('progress-pct'); if(pp) pp.textContent=pct+'%';
}

/* ── 7. HELP MODAL ───────────────────────────────────────────────── */
function openHelpModal(){ const m=$('help-modal'); if(m) m.style.display='flex'; }
