/**
 * AMPS CCMC — AMPS_PARAM.IN BUILDER
 * Generates the full AMPS_PARAM.in SWMF #BLOCK namelist
 * from the current STATE object and renders it into the
 * review panel and sidebar preview.
 */

'use strict';
import { STATE, getShueParams, fmt1, fmt2, fmt3 } from './core.js';

const HEADER = `! ═══════════════════════════════════════════════════════════════
! AMPS_PARAM.in  —  generated by CCMC Runs-on-Request interface
! Run: ${STATE.runName || 'unnamed'}
! ═══════════════════════════════════════════════════════════════
`;

function line(key, val, comment='') {
  const k = key.padEnd(22);
  const v = String(val).padEnd(16);
  return `${k}${v}${comment ? '! '+comment : ''}`;
}

export function buildParamFile() {
  const p = STATE;
  const shue = getShueParams();

  const blocks = [];

  /* ── RUN METADATA ── */
  blocks.push([
    `#RUN_INFO`,
    line('RUN_ID',          p.runName || 'unnamed'),
    line('PI_NAME',         p.piName  || 'Unknown'),
    line('PI_EMAIL',        p.piEmail || 'unknown@unknown.edu'),
    line('INSTITUTION',     p.institution || 'Unknown'),
    line('SCIENCE_GOAL',    p.scienceGoal),
    '',
  ].join('\n'));

  /* ── PARTICLE SPECIES ── */
  blocks.push([
    `#PARTICLE_SPECIES`,
    line('SPECIES',         p.species.toUpperCase()),
    line('CHARGE',          p.chargeState,        'elementary charge units'),
    line('MASS_AMU',        p.massAMU,            'atomic mass units'),
    '',
  ].join('\n'));

  /* ── BACKGROUND FIELD ── */
  blocks.push([
    `#BACKGROUND_FIELD`,
    line('FIELD_MODEL',     p.fieldModel),
    line('TS05_DST',        fmt1(p.dst),           'nT — ring current index'),
    line('TS05_PDYN',       fmt2(p.pdyn),          'nPa — dynamic pressure'),
    line('TS05_BZ',         fmt2(p.bz),            'nT — IMF Bz GSM'),
    line('TS05_VX',         fmt1(p.vx),            'km/s — solar wind Vx GSM'),
    line('TS05_NSW',        fmt2(p.nsw),           'cm-3 — proton density'),
    line('TS05_BY',         fmt2(p.by),            'nT — IMF By GSM'),
    line('TS05_BX',         fmt2(p.bx),            'nT — IMF Bx GSM'),
    line('EPOCH',           p.epoch,              'UTC timestamp'),
    '',
  ].join('\n'));

  /* ── DOMAIN BOUNDARY ── */
  if(p.boundaryType === 'BOX') {
    blocks.push([
      `#DOMAIN_BOUNDARY`,
      line('BOUNDARY_TYPE',   'BOX',                'rectangular cuboid in GSM'),
      line('DOMAIN_X_MAX',    fmt1(p.boxXmax),      'RE dayside'),
      line('DOMAIN_X_MIN',    fmt1(p.boxXmin),      'RE nightside tail'),
      line('DOMAIN_Y_MAX',    fmt1(p.boxYmax),      'RE dusk flank'),
      line('DOMAIN_Y_MIN',    fmt1(p.boxYmin),      'RE dawn flank'),
      line('DOMAIN_Z_MAX',    fmt1(p.boxZmax),      'RE north polar'),
      line('DOMAIN_Z_MIN',    fmt1(p.boxZmin),      'RE south polar'),
      line('R_INNER',         fmt1(p.boxRinner),    'RE inner loss sphere'),
      '',
    ].join('\n'));
  } else {
    const r0str    = p.shueMode === 'manual' ? fmt2(shue.r0)    : 'AUTO';
    const alphaStr = p.shueMode === 'manual' ? fmt3(shue.alpha) : 'AUTO';
    blocks.push([
      `#DOMAIN_BOUNDARY`,
      line('BOUNDARY_TYPE',   'SHUE',               'Shue et al. 1998 magnetopause'),
      line('SHUE_R0',         r0str,                'RE; AUTO = from TS05 Bz,Pdyn'),
      line('SHUE_ALPHA',      alphaStr,             'AUTO = from TS05 Bz,Pdyn'),
      line('DOMAIN_X_TAIL',   fmt1(p.xtail),        'RE flat nightside cap'),
      line('R_INNER',         fmt1(p.shueRinner),   'RE inner loss sphere'),
      '',
    ].join('\n'));
  }

  /* ── TEMPORAL VARIABILITY ── */
  blocks.push([
    `#TEMPORAL`,
    line('TEMPORAL_MODE',   p.temporalMode),
    ...(p.temporalMode !== 'STEADY_STATE' ? [
      line('EVENT_START',     p.eventStart,         'UTC'),
      line('EVENT_END',       p.eventEnd,           'UTC'),
      line('FIELD_UPDATE_DT', p.fieldUpdateDt,      'min — TS05 refresh cadence'),
      line('INJECT_DT',       p.injectDt,           'min — particle injection interval'),
      line('TS_INPUT_MODE',   p.tsSource === 'omni' ? 'OMNIWEB' :
                              p.tsSource === 'file' ? 'FILE'    : 'SCALAR'),
    ] : [
      line('EPOCH',           p.epoch,              'UTC snapshot'),
    ]),
    '',
  ].join('\n'));

  /* ── SPECTRUM / BOUNDARY CONDITION ── */
  blocks.push([
    `#SPECTRUM`,
    line('SPECTRUM_TYPE',   p.spectrumType),
    ...(p.spectrumType === 'POWER_LAW' ? [
      line('SPEC_J0',        p.specJ0.toExponential(2), 'particles/cm2/s/sr/(MeV/n)'),
      line('SPEC_GAMMA',     fmt2(p.specGamma),     'spectral index'),
      line('SPEC_E0',        fmt1(p.specE0),        'MeV/n pivot energy'),
    ] : p.spectrumType === 'BAND' ? [
      line('BAND_J0',        p.specJ0.toExponential(2)),
      line('BAND_GAMMA1',    fmt2(p.specGamma)),
      line('BAND_GAMMA2',    '1.50'),
      line('BAND_E0',        fmt1(p.specE0)),
    ] : [
      line('SPEC_TABLE_FILE','sep_spectrum_H+.txt', 'E[MeV/n] dJ/dE columns'),
    ]),
    line('SPEC_EMIN',       fmt1(p.specEmin),       'MeV/n'),
    line('SPEC_EMAX',       fmt1(p.specEmax),       'MeV/n'),
    '',
  ].join('\n'));

  /* ── OUTPUT DOMAIN ── */
  blocks.push([
    `#OUTPUT_DOMAIN`,
    line('OUTPUT_MODE',     p.outputMode),
    ...(p.outputMode === 'TRAJECTORY' ? [
      line('TRAJ_FILE',     'trajectory.txt',       'NAIRAS Gregorian or MJD format'),
      line('FLUX_DT',       fmt1(p.fluxDt),         'min — output cadence along track'),
    ] : p.outputMode === 'SHELLS' ? [
      line('SHELL_COUNT',   '1'),
      line('SHELL_ALT_1',   '450.0',                'km — ISS orbit'),
    ] : [
      line('POINT_FILE',    'points.txt',           'lat lon alt list'),
    ]),
    '',
  ].join('\n'));

  /* ── OUTPUT OPTIONS ── */
  blocks.push([
    `#OUTPUT_OPTIONS`,
    line('FLUX_TYPE',       p.outputFluxType,       'DIFFERENTIAL | INTEGRAL'),
    line('OUTPUT_CUTOFF',   p.outputCutoff  ? 'T' : 'F', 'cutoff rigidity maps'),
    line('OUTPUT_PITCH',    p.outputPitch   ? 'T' : 'F', 'pitch angle distributions'),
    line('OUTPUT_FORMAT',   p.outputFormat,         'NETCDF4 | HDF5 | ASCII'),
    line('OUTPUT_COORDS',   p.outputCoords,         'GEO | GSM | SM'),
    `ENERGY_BINS           ${(p.energyBins||[]).join(' ')}   ! MeV/n`,
    '',
  ].join('\n'));

  /* ── NUMERICAL PARAMETERS ── */
  blocks.push([
    `#NUMERICAL`,
    line('N_PARTICLES',     '10000',                'test particles per injection'),
    line('MAX_BOUNCE',      '500',                  'max mirror reflections'),
    line('DT_TRACE',        '1.0',                  's — time step for tracing'),
    line('PITCH_ISOTROPIC', 'T',                    'isotropic injection at boundary'),
    '',
  ].join('\n'));

  const full = HEADER + '\n' + blocks.join('\n') + '\n#END\n';

  /* Render into review panel */
  const el = document.getElementById('review-param');
  if(el) {
    el.textContent = '';
    // Syntax-highlight: section headers, keys, values, comments
    el.innerHTML = full
      .replace(/^(#\w+)/gm, '<span class="r-section">$1</span>')
      .replace(/^(\w[\w_]+)(\s+)(\S+)(\s*)(! .+)?$/gm, (_, k, s1, v, s2, c) =>
        `<span class="r-key">${k}</span>${s1}<span class="r-val">${v}</span>${s2}${c?`<span class="r-comment">${c}</span>`:''}`)
      .replace(/(AUTO)/g, '<span class="r-auto">AUTO</span>');
  }

  /* Render into sidebar mini-preview */
  const sb = document.getElementById('sb-param-preview');
  if(sb) {
    const mini = blocks.slice(0, 3).join('\n').split('\n').slice(0, 18).join('\n') + '\n…';
    sb.textContent = mini;
  }

  return full;
}
