/**
 * AMPS CCMC — paramfile.js
 * Generates the complete AMPS_PARAM.in file from AMPS.state.
 * Follows the SWMF #BLOCK namelist format.
 */
(function () {
  'use strict';
  window.AMPS = window.AMPS || {};

  AMPS.paramfile = {

    generate: function () {
      var s   = AMPS.state;
      var now = new Date().toISOString();
      var L   = [];   // line buffer

      function w  (line) { L.push(line); }
      function nl ()     { L.push(''); }
      function hr ()     { L.push('!' + '─'.repeat(72)); }
      function sec(name) { nl(); hr(); w('! ' + name); hr(); nl(); }
      function kw (key, val, unit, comment) {
        var vStr = val === null || val === undefined ? '' : String(val);
        var pad  = Math.max(1, 24 - key.length);
        var line = key + ' '.repeat(pad) + vStr;
        if (unit)    line += '  ! [' + unit + ']';
        if (comment && !unit) line += '  ! ' + comment;
        if (comment &&  unit) line += ' ' + comment;
        w(line);
      }
      function block (name) { w('#' + name); }

      // ── File header ──────────────────────────────────────────────────
      w('! ═══════════════════════════════════════════════════════════════════');
      w('! AMPS_PARAM.in  —  Automated Magnetospheric Particle Simulator');
      w('! Generated by CCMC RoR Interface  ' + now);
      w('! Model version: AMPS ' + (s.amps_version || '2025.1'));
      w('! DO NOT EDIT — regenerate from the CCMC submission interface');
      w('! ═══════════════════════════════════════════════════════════════════');
      nl();

      // ── Run Information ───────────────────────────────────────────────
      sec('SECTION 1: RUN INFORMATION');
      block('RUN_INFO');
      kw('RUN_TITLE',       '"' + (s.run_title || 'Untitled') + '"');
      kw('RUN_DESCRIPTION', '"' + (s.run_description || '').replace(/"/g,"'").slice(0,120) + '"');
      kw('PI_NAME',         '"' + (s.pi_name || '') + '"');
      kw('PI_EMAIL',        '"' + (s.pi_email || '') + '"');
      kw('PI_INSTITUTION',  '"' + (s.pi_institution || '') + '"');
      kw('RUN_PURPOSE',     s.run_purpose || 'SCIENCE',
         null, 'VALIDATION | SCIENCE | OPERATIONAL | OTHER');
      kw('KEYWORDS',        '"' + (s.run_keywords || '') + '"');
      nl();

      // ── Particle configuration ────────────────────────────────────────
      sec('SECTION 2: PARTICLE CONFIGURATION');
      block('SIMULATION');
      kw('SIM_TYPE',    s.sim_type, null, 'SEP | GCR | COMBINED');
      kw('N_PARTICLES', s.n_particles + '', null, 'total test particles (per species)');
      nl();
      block('SPECIES');
      if (s.species_H)   kw('H_PLUS',   'ON', null, 'protons (primary SEP species)');
      if (s.species_He)  kw('HE2_PLUS', 'ON', null, 'alpha particles');
      if (s.species_e)   kw('ELECTRON', 'ON', null, 'electrons (experimental)');
      if (s.species_GCR) kw('GCR_P',    'ON', null, 'GCR protons (Badhwar-ONeill)');
      nl();
      block('ENERGY_RANGE');
      kw('E_MIN',      s.energy_min + '',  'MeV/n');
      kw('E_MAX',      s.energy_max + '',  'MeV/n');
      kw('E_BINS',     s.energy_bins + '', null, 'logarithmically spaced');
      nl();
      block('PITCH_ANGLE');
      kw('PITCH_DIST', s.pitch_angle || 'ISOTROPIC',
         null, 'ISOTROPIC | CONE30 | UNIDIRECTIONAL | CUSTOM');
      if (s.pitch_angle === 'CONE30' || s.pitch_angle === 'UNIDIRECTIONAL') {
        kw('CONE_HALF_ANGLE', (s.pitch_cone_half || 30) + '', 'deg');
      }
      nl();

      // ── Background Field ──────────────────────────────────────────────
      sec('SECTION 3: GEOMAGNETIC BACKGROUND FIELD');
      block('BFIELD_MODEL');
      kw('MODEL',        s.bfield_model || 'TS05',
         null, 'TS05 | TA15 | BATSRUS | GAMERA | IGRF | DIPOLE');
      if (s.bfield_model === 'TS05' || s.bfield_model === 'TA15') {
        kw('TS_VERSION', s.ts_version || 'TS05');
      }
      if (s.bfield_model === 'BATSRUS' || s.bfield_model === 'GAMERA') {
        kw('MHD_RUN_ID', '"' + (s.mhd_run_id || '') + '"');
      }
      nl();
      block('TS_DRIVING');
      kw('TS_INPUT_MODE', s.ts_input_mode,
         null, 'SCALAR | TIME_SERIES | OMNIWEB');
      if (s.ts_input_mode === 'SCALAR') {
        kw('DST',  s.ts_dst  + '', 'nT',    'ring current index');
        kw('PDYN', s.ts_pdyn + '', 'nPa',   'solar wind dynamic pressure');
        kw('IMF_BZ', s.ts_bz + '', 'nT',    'southward < 0');
        kw('SW_VX',  s.ts_vx + '', 'km/s',  'anti-sunward < 0');
        kw('SW_NSW', s.ts_nsw+ '', 'cm-3',  'proton number density');
        kw('IMF_BY', s.ts_by + '', 'nT');
        kw('IMF_BX', s.ts_bx + '', 'nT');
        kw('EPOCH',  s.ts_epoch || '', null, 'UTC ISO format');
      } else if (s.ts_input_mode === 'TIME_SERIES') {
        kw('TS_FILE', 'ts05_driving.txt');
      } else {
        kw('OMNIWEB_AUTO', 'YES', null, 'CCMC fetches from omniweb.gsfc.nasa.gov');
        kw('OMNIWEB_CADENCE', s.omni_cadence || '5min');
      }
      nl();
      block('EFIELD_MODEL');
      kw('EFIELD_TYPE', s.efield_model || 'VXB',
         null, 'NONE | VXB | MHD');
      kw('COROTATION',  s.corotation ? 'YES' : 'NO');
      nl();

      // ── Temporal Variability ──────────────────────────────────────────
      sec('SECTION 4A: TEMPORAL VARIABILITY');
      block('TEMPORAL');
      kw('TEMPORAL_MODE', s.temporal_mode,
         null, 'STEADY_STATE | TIME_SERIES | COUPLED_MHD');
      if (s.temporal_mode !== 'STEADY_STATE') {
        kw('EVENT_START',     s.event_start || '', null, 'UTC');
        kw('EVENT_END',       s.event_end   || '', null, 'UTC');
        kw('FIELD_UPDATE_DT', (s.field_update_dt || 5) + '', 'min',
           'TS05 refresh cadence');
        kw('INJECT_DT',       (s.inject_dt || 30) + '', 'min',
           'particle injection batch interval; must be >= FIELD_UPDATE_DT');
      }
      nl();

      // ── Spectrum ──────────────────────────────────────────────────────
      sec('SECTION 4B: PARTICLE SPECTRUM');
      block('SPECTRUM');
      kw('SPECTRUM_TYPE', s.spectrum_type,
         null, 'MOTTL_NYMMIK | BAND | TABLE | GOES_AUTO | BADHWAR_ONEILL');
      if (s.spectrum_type === 'BAND') {
        w('!');
        w('! Band (1993) double power-law:');
        w('!   dJ/dE = J0*(E/Eb)^g1*exp(-E/Eb)  for E<Eb');
        w('!   dJ/dE = J0*((g1-g2)*Eb)^(g1-g2)*exp(g2-g1)*E^g2  for E>=Eb');
        w('!');
        kw('BAND_GAMMA1', s.band_gamma1 + '', null, 'low-energy power-law index');
        kw('BAND_GAMMA2', s.band_gamma2 + '', null, 'high-energy power-law index (steeper)');
        kw('BAND_EBREAK', s.band_ebreak + '', 'MeV/n', 'spectral break energy');
        kw('BAND_J0',     s.band_j0 + '',     'cm-2 s-1 sr-1 (MeV/n)-1');
      } else if (s.spectrum_type === 'TABLE') {
        if (s.species_H)  kw('SPECTRUM_FILE_H',  'sep_spectrum_H.txt');
        if (s.species_He) kw('SPECTRUM_FILE_HE', 'sep_spectrum_He.txt');
      } else if (s.spectrum_type === 'BADHWAR_ONEILL') {
        kw('GCR_MODEL', s.gcr_model || 'BO2014');
        kw('GCR_PHI',   (s.gcr_phi || 550) + '', 'MV', 'solar modulation potential');
      } else if (s.spectrum_type === 'GOES_AUTO') {
        kw('GOES_EPOCH', s.ts_epoch || '', null, 'use TS05 epoch for GOES lookup');
      }
      nl();

      // ── Domain Boundary ───────────────────────────────────────────────
      sec('SECTION 5A: SIMULATION DOMAIN BOUNDARY');
      block('DOMAIN_BOUNDARY');
      kw('BOUNDARY_TYPE', s.boundary_type, null, 'BOX | SHUE');
      if (s.boundary_type === 'BOX') {
        w('!');
        w('! Rectangular box in GSM coordinates (Earth radii).');
        w('! +X_GSM = sunward, +Z_GSM = northward (dipole-aligned in GSM)');
        w('!');
        kw('DOMAIN_X_MAX', (s.box_xmax || 15) + '', 'RE', 'dayside');
        kw('DOMAIN_X_MIN', (s.box_xmin || -60) + '', 'RE', 'nightside tail');
        kw('DOMAIN_Y_MAX', (s.box_ymax || 25) + '', 'RE', 'dusk flank');
        kw('DOMAIN_Y_MIN', (s.box_ymin || -25) + '', 'RE', 'dawn flank');
        kw('DOMAIN_Z_MAX', (s.box_zmax || 20) + '', 'RE', 'north');
        kw('DOMAIN_Z_MIN', (s.box_zmin || -20) + '', 'RE', 'south');
        kw('R_INNER',      (s.box_rinner || 2.0) + '', 'RE', 'inner loss sphere');
      } else {
        w('!');
        w('! Shue et al. (1998) empirical magnetopause model:');
        w('!   r(theta) = r0 * (2/(1+cos(theta)))^alpha');
        w('!   r0    = (11.4 + 0.013*Bz) * Pdyn^(-1/6.6)');
        w('!   alpha = (0.58 - 0.007*Bz) * (1 + 0.024*ln(Pdyn))');
        w('! Nightside closed by flat tail-cap at X_TAIL.');
        w('!');
        kw('SHUE_R0',    s.shue_mode === 'MANUAL' ? (s.shue_r0 || 8.56) + '' : 'AUTO',
           'RE', 'AUTO = computed from TS05 Pdyn, Bz at each time step');
        kw('SHUE_ALPHA', s.shue_mode === 'MANUAL' ? (s.shue_alpha || 0.617) + '' : 'AUTO',
           null, 'AUTO = computed from TS05 Pdyn, Bz at each time step');
        kw('X_TAIL',     (s.shue_xtail || -60) + '', 'RE', 'flat nightside cap');
        kw('R_INNER',    (s.shue_rinner || 2.0) + '', 'RE', 'inner loss sphere');
      }
      nl();

      // ── Output Domain ─────────────────────────────────────────────────
      sec('SECTION 5B: OUTPUT DOMAIN');
      block('OUTPUT_DOMAIN');
      kw('OUTPUT_MODE',   s.output_mode,
         null, 'POINTS | TRAJECTORY | SHELLS');
      if (s.output_mode === 'POINTS') {
        kw('OUTPUT_COORD', s.output_coord || 'GEO', null, 'GEO | GSM | SM');
      }
      if (s.output_mode === 'TRAJECTORY') {
        kw('TRAJECTORY_FILE',  s.trajectory_file_name || 'trajectory.txt');
        kw('TRAJECTORY_COORD', s.trajectory_coord || 'GEO', null, 'NAIRAS Gregorian format');
        kw('FLUX_DT',          (s.flux_dt || 1.0) + '', 'min', 'output interval along track');
        if (s.extra_shell_alt > 0) {
          kw('EXTRA_SHELL_ALT', s.extra_shell_alt + '', 'km', 'concurrent shell output');
        }
      }
      if (s.output_mode === 'SHELLS') {
        kw('N_SHELLS',      s.n_shells + '');
        kw('SHELL_1_ALT',   s.shell_1_alt + '', 'km');
        if (s.n_shells >= 2 && s.shell_2_alt > 0) kw('SHELL_2_ALT', s.shell_2_alt + '', 'km');
        if (s.n_shells >= 3 && s.shell_3_alt > 0) kw('SHELL_3_ALT', s.shell_3_alt + '', 'km');
        kw('SHELL_LAT_MIN',  s.shell_lat_min + '', 'deg');
        kw('SHELL_LAT_MAX',  s.shell_lat_max + '', 'deg');
        kw('SHELL_LAT_STEP', s.shell_lat_step + '', 'deg');
        kw('SHELL_LON_MIN',  s.shell_lon_min + '', 'deg');
        kw('SHELL_LON_MAX',  s.shell_lon_max + '', 'deg');
        kw('SHELL_LON_STEP', s.shell_lon_step + '', 'deg');
      }
      nl();

      // ── Output Options ────────────────────────────────────────────────
      sec('SECTION 6: OUTPUT OPTIONS');
      block('OUTPUT_OPTIONS');
      kw('OUTPUT_FORMAT',    s.output_format,
         null, 'ASCII | CDF | NETCDF4 | HDF5');
      kw('CUTOFF_RIGIDITY',  s.cutoff_rigidity   ? 'YES' : 'NO');
      kw('KAMODO_OUTPUT',    s.kamodo_output     ? 'YES' : 'NO');
      kw('DIST_FUNCTION',    s.dist_function     ? 'YES' : 'NO');
      kw('SAVE_TRAJECTORIES', s.save_trajectories || 'NONE',
         null, 'NONE | SAMPLE_1000 | ALL');
      kw('COLORMAP',          s.colormap || 'VIRIDIS');
      if (s.email_notify) {
        kw('EMAIL_NOTIFY',   '"' + s.email_notify + '"');
      }
      nl();

      // ── Footer ────────────────────────────────────────────────────────
      w('! ═══════════════════════════════════════════════════════════════════');
      w('! END OF AMPS_PARAM.in');
      w('! Submission time: ' + now);
      w('! Run ID will be assigned by CCMC HPC scheduler.');
      w('! ═══════════════════════════════════════════════════════════════════');
      w('#END');
      nl();

      return L.join('\n');
    }

  };
}());
